import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const dir=mkdtempSync(join(tmpdir(),'companies-'));process.env.DB_PATH=join(dir,'test.db');process.env.NODE_ENV='test';const {server}=await import('../server.js');let base;
before(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port});after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true})});
async function api(path,opt={}){const r=await fetch(base+path,{headers:{'content-type':'application/json'},...opt});return {status:r.status,body:await r.json()}}
let id;
test('database starts empty',async()=>{const r=await api('/api/companies');assert.equal(r.status,200);assert.equal(r.body.total,0)});
test('validation and add company',async()=>{let r=await api('/api/companies',{method:'POST',body:JSON.stringify({name:'Без ИНН'})});assert.equal(r.status,400);r=await api('/api/companies',{method:'POST',body:JSON.stringify({name:'Тест <script>alert(1)</script>','inn':'A-1','industry':'Робототехника','phone':'+998 90 123 45 67'})});assert.equal(r.status,201);id=r.body.id;assert.equal(r.body.inn,'A-1')});
test('global search across fields',async()=>{for(const q of ['робототехника','123 45','A-1']){const r=await api('/api/companies?q='+encodeURIComponent(q));assert.equal(r.body.total,1)}});
test('atomic booking conflict and owner-only release',async()=>{const [a,b]=await Promise.all([api('/api/companies/'+id+'/reserve',{method:'POST',body:JSON.stringify({team:'Таллин'})}),api('/api/companies/'+id+'/reserve',{method:'POST',body:JSON.stringify({team:'Токио'})})]);assert.deepEqual([a.status,b.status].sort(),[200,409]);const winner=(a.status===200?a:b).body.reserved_by;const loser=winner==='Таллин'?'Токио':'Таллин';let r=await api('/api/companies/'+id+'/release',{method:'POST',body:JSON.stringify({team:loser})});assert.equal(r.status,403);r=await api('/api/companies/'+id+'/release',{method:'POST',body:JSON.stringify({team:winner})});assert.equal(r.status,200);assert.equal(r.body.status,'free')});
test('edit, filters and history',async()=>{let r=await api('/api/companies/'+id,{method:'PUT',body:JSON.stringify({name:'Обновлённая компания','inn':'A-1','address':'Ташкент'})});assert.equal(r.status,200);assert.equal(r.body.address,'Ташкент');r=await api('/api/companies?status=free');assert.equal(r.body.total,1);r=await api('/api/companies/'+id+'/history');assert.ok(r.body.items.some(x=>x.action==='updated'));assert.equal(r.body.items.filter(x=>x.action==='reserved').length,1);assert.equal(r.body.items.filter(x=>x.action==='released').length,1)});
