import * as React from 'react'; import * as DialogPrimitive from '@radix-ui/react-dialog'; import {X} from 'lucide-react'; import {cn} from '@/lib/utils'
const Dialog=DialogPrimitive.Root,DialogTrigger=DialogPrimitive.Trigger,DialogClose=DialogPrimitive.Close,DialogPortal=DialogPrimitive.Portal
const DialogOverlay=React.forwardRef(({className,...p},r)=><DialogPrimitive.Overlay ref={r} className={cn('fixed inset-0 z-50 bg-slate-950/75 backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out',className)} {...p}/>);DialogOverlay.displayName='DialogOverlay'
const DialogContent=React.forwardRef(({className,children,...p},r)=><DialogPortal><DialogOverlay/><DialogPrimitive.Content ref={r} className={cn('fixed left-1/2 top-1/2 z-50 grid max-h-[92vh] w-[calc(100%-2rem)] max-w-2xl -translate-x-1/2 -translate-y-1/2 gap-4 overflow-y-auto rounded-2xl border border-border bg-popover p-6 shadow-2xl',className)} {...p}>{children}<DialogPrimitive.Close className='absolute right-4 top-4 rounded-md p-1 text-muted-foreground hover:bg-accent hover:text-foreground focus:outline-none focus:ring-2 focus:ring-ring'><X className='h-4 w-4'/><span className='sr-only'>Закрыть</span></DialogPrimitive.Close></DialogPrimitive.Content></DialogPortal>);DialogContent.displayName='DialogContent'
const DialogHeader=({className,...p})=><div className={cn('flex flex-col space-y-1.5 text-left',className)} {...p}/>
const DialogFooter=({className,...p})=><div className={cn('flex flex-col-reverse gap-2 sm:flex-row sm:justify-end',className)} {...p}/>
const DialogTitle=React.forwardRef(({className,...p},r)=><DialogPrimitive.Title ref={r} className={cn('text-xl font-semibold leading-none tracking-tight',className)} {...p}/>);DialogTitle.displayName='DialogTitle'
const DialogDescription=React.forwardRef(({className,...p},r)=><DialogPrimitive.Description ref={r} className={cn('text-sm text-muted-foreground',className)} {...p}/>);DialogDescription.displayName='DialogDescription'
export {Dialog,DialogTrigger,DialogClose,DialogContent,DialogHeader,DialogFooter,DialogTitle,DialogDescription}
